In [10]:
import pyodbc
import pandas as pd
import json

In [24]:
with open('D:\Azfar\Personal\Programming_Projects\PIAIC\Quarter2\config.json', 'r') as f:
    dbConfig = json.load(f)

dbConfig
#sqlConnection = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)

{'server': '234567890',
 'database': '21313ddsaeqwe',
 'username': 'asdlkjasdkljasdkl',
 'password': 'asdkljaslkjasdkl'}

In [111]:
#PARAMETERS
emailId = "az.test"
entityId = 575
entityName = 'Pride'

In [1]:
#GET SQL Query FROM A FILE AND ADD PARAMETERS
filePath = 'data/get_invoice_details.sql'
with open(filePath) as file:
    query = (file.read()).format(entityName = entityName)
query

NameError: name 'entityName' is not defined

In [113]:
df = pd.read_sql(query, sqlConnection)
df.head(5)

,OriginalInvoiceId,DocumentId,ProcessingStatus,DocumentSubType,InvoiceNo,InvoiceDate,DueDate,TransactionCurrency,BaseCurrency,EntityInformationBaseCurrency,...,CategoryID,CategoryName,PaymentMethodID,PaymentMethodName,VATID,VATName,Percentage,Details,CommentText,FilePath
0,9753,NaN,Modified,None,None,NaT,NaT,None,None,GBP,...,NaN,None,NaN,None,NaN,None,NaN,None,None,app.receipt-bot.com/DocumentStorage/366_636635...
1,9756,NaN,Modified,None,None,NaT,NaT,None,None,GBP,...,NaN,None,NaN,None,NaN,None,NaN,None,None,app.receipt-bot.com/DocumentStorage/366_636635...
2,9751,NaN,Modified,None,None,NaT,NaT,None,None,GBP,...,NaN,None,NaN,None,NaN,None,NaN,None,None,app.receipt-bot.com/DocumentStorage/366_636635...
3,9737,NaN,Modified,None,None,NaT,NaT,None,None,GBP,...,NaN,None,NaN,None,NaN,None,NaN,None,None,app.receipt-bot.com/DocumentStorage/366_636635...
4,9752,NaN,Modified,None,None,NaT,NaT,None,None,GBP,...,NaN,None,NaN,None,NaN,None,NaN,None,None,app.receipt-bot.com/DocumentStorage/366_636635...

In [138]:
supplierList = df['SupplierName'].value_counts()
for i in supplierList.items():
    print(i[0], i[1])

Travis Parkins  67
City Plumbing 33
Hewett Electrical Supplies Ltd 20
Waytrix 5
Brixham Garage 4
Rainbow Skips and Recycling Ltd 4
S Lambe 3
Dean Kilpatrick 3
Howdens Joinery Co 2
Arc Steel Projects Ltd 1

In [151]:
supplierCategoryCompare = df[['DocumentId','SupplierName','CategoryName','ProcessingStatus']]
supplierCategoryCompare

     DocumentId   SupplierName       CategoryName ProcessingStatus
0           NaN           None               None         Modified
1           NaN           None               None         Modified
2           NaN           None               None         Modified
3           NaN           None               None         Modified
4           NaN           None               None         Modified
5           NaN           None               None         Modified
6           1.0  City Plumbing  Materials Expense         Approved
7           2.0  City Plumbing  Materials Expense         Approved
8           3.0  City Plumbing  Materials Expense         Approved
9           4.0  City Plumbing  Materials Expense         Approved
10          5.0  City Plumbing  Materials Expense         Approved
11          6.0  City Plumbing  Materials Expense         Approved
12          7.0  City Plumbing  Materials Expense         Approved
13          8.0  City Plumbing  Materials Expense         Approved
14          9.0           None               None          Deleted
15         10.0  City Plumbing  Materials Expense         Approved
16         11.0  City Plumbing  Materials Expense     Data Entered
17         12.0  City Plumbing  Materials Expense         Approved
18         13.0  City Plumbing          Bank Fees         Approved
19         14.0  City Plumbing  Materials Expense         Approved
20         15.0  City Plumbing  Materials Expense     Data Entered
21         16.0  City Plumbing  Materials Expense     Data Entered
22         17.0  City Plumbing  Materials Expense     Data Entered
23         18.0  City Plumbing  Materials Expense     Data Entered
24         19.0  City Plumbing  Materials Expense     Data Entered
25         20.0  City Plumbing          Purchases     Data Entered
26         21.0  City Plumbing          Purchases     Data Entered
27         22.0  City Plumbing          Purchases     Data Entered
28         23.0           None               None          Deleted
29         24.0  City Plumbing          Purchases     Data Entered
..          ...            ...                ...              ...
237       238.0           None               None         Modified
238       239.0           None               None         Modified
239       240.0           None               None         Modified
240       241.0           None               None         Modified
241       242.0           None               None         Modified
242       243.0           None               None         Modified
243       244.0           None               None         Modified
244       245.0           None               None         Modified
245       246.0           None               None         Modified
246       247.0           None               None         Modified
247       248.0           None               None         Modified
248       249.0           None               None         Modified
249       250.0           None               None         Modified
250       251.0           None               None         Modified
251       252.0           None               None         Modified
252       253.0           None               None         Modified
253       254.0           None               None         Modified
254       255.0           None               None         Modified
255       256.0           None               None         Modified
256       257.0           None               None         Modified
257       258.0           None               None         Modified
258       259.0           None               None         Modified
259       260.0           None               None         Modified
260       261.0           None               None         Modified
261       262.0           None               None         Modified
262       263.0           None               None         Modified
263       264.0           None               None         Modified
264       265.0           None               None         Modified
265       266.0           None               None         Modified
266       267.0           None               None         Modified

[267 rows x 4 columns]